version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:8.0-fpm-alpine
    volumes:
      - ./public:/var/www/html
